Modified script and readme for Wayland and Wofi; removed man pages and Makefile

diff --git a/menu-qalc b/menu-qalc
--- a/menu-qalc
+++ b/menu-qalc
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
 # https://github.com/onespaceman/menu-calc
-# Calculator for use with rofi/dmenu(2)
-# Copying to the clipboard requires xclip
+# Calculator for use with wofi/dmenu(2)
+# Copying to the clipboard requires wl-clipboard
 
 usage() {
     echo "$(tput bold)menu-calc$(tput sgr0)"
-    echo "A calculator for Rofi/dmenu(2)"
+    echo "A calculator for Wofi/dmenu(2)"
     echo
     echo "$(tput bold)Usage:$(tput sgr0)"
     echo "    = 4+2"
@@ -15,20 +15,20 @@ usage() {
     echo "    = sqrt(4)"
     echo "    = c(2)"
     echo
-    echo "$(tput bold)Force Rofi/dmenu(2):$(tput sgr0)"
-    echo "By default, if rofi exists, it will be used. To force menu-calc to"
+    echo "$(tput bold)Force Wofi/dmenu(2):$(tput sgr0)"
+    echo "By default, if wofi exists, it will be used. To force menu-calc to"
     echo "use one or the other, use the --dmenu argument"
     echo
     echo "    = --dmenu=<dmenu_executable>"
     echo
-    echo "$(tput bold)Passing arguments to Rofi/dmenu(2):$(tput sgr0)"
-    echo "Any parameters after ' -- ' will be passed to Rofi/dmenu(2)."
+    echo "$(tput bold)Passing arguments to Wofi/dmenu(2):$(tput sgr0)"
+    echo "Any parameters after ' -- ' will be passed to Wofi/dmenu(2)."
     echo
-    echo "    = -- <Rofi/dmenu(2) args>"
+    echo "    = -- <Wofi/dmenu(2) args>"
     echo
-    echo "The answer can be copied to the clipboard and used for further calculations inside (or outside) Rofi/dmenu."
+    echo "The answer can be copied to the clipboard and used for further calculations inside (or outside) Wofi/dmenu."
     echo
-    echo "If launched outside of Rofi/dmenu the expression may need quotation marks."
+    echo "If launched outside of Wofi/dmenu the expression may need quotation marks."
     exit
 }
 
@@ -51,24 +51,24 @@ fi
 
 # Path to menu application
 if [ -z "${menu+1}" ]; then
-    if [[ -n $(command -v rofi) ]]; then
-        menu="$(command -v rofi)"
+    if [[ -n $(command -v wofi) ]]; then
+        menu="$(command -v wofi)"
     elif [[ -n $(command -v dmenu) ]]; then
         menu=$(command -v dmenu)
     else
-        >&2 echo "Rofi or dmenu not found"
+        >&2 echo "Wofi or dmenu not found"
         exit
     fi
 fi
 
-# If using rofi, add the necessary parameters
-if [[ $menu == "rofi" || $menu == $(command -v rofi) ]]; then
-    menu="$menu -dmenu -lines 3"
+# If using wofi, add the necessary parameters
+if [[ $menu == "wofi" || $menu == $(command -v wofi) ]]; then
+    menu="$menu --dmenu"
 elif [[ $menu == "dmenu" || $menu == $(command -v dmenu) ]]; then
     menu="$menu ""$DMENU_OPTIONS"
 fi
 
-# Determine args to pass to dmenu/rofi
+# Determine args to pass to dmenu/wofi
 while [[ $# -gt 0 && $1 != "--" ]]; do
     shift
 done
@@ -78,7 +78,7 @@ action=$(echo -e "Copy to clipboard\nClear\nClose" | $menu "$@" -p "= $answer")
 
 case $action in
     "Clear") $0 ;;
-    "Copy to clipboard") echo -n "$answer" | xclip -selection clipboard ;;
+    "Copy to clipboard") echo -n "$answer" | wl-copy ;;
     "Close") ;;
     "") ;;
     *) $0 "$answer $action" "--dmenu=$menu" "--" "$@" ;;
